plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.+'
}

group = 'com.viameowts.viapanel'
base.archivesName = 'viapanel'
version = project.mod_version + "+mc" + project.minecraft_version

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraft:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
               "loader_version": project.loader_version,
               "minecraft_version": project.minecraft_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(25)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

artifacts {
    archives sourcesJar
}
